

vegan_substitutions = {
    "dairy": {
        "butter": "vegan margarine",
        "milk": "almond milk",
        "heavy cream": "coconut cream",
        "sour cream": "vegan sour cream",
        "yogurt": "coconut yogurt",
        "cheese": "vegan cheese",
        "buttermilk": "curdled soymilk"
    },
    "eggs": {
        "eggs": "tofu",
        "mayonnaise": "vegan mayonnaise"
    },
    "meat": {
        "chicken": "seitan",
        "beef patties": "bean patties",
        "beef": "tempeh",
        "pork": "jackfruit",
        "bacon": "tempeh bacon",
        "sausage": "vegan sausage",
        "ground beef": "soy crumbles",
        "lamb": "eggplant",
        "turkey": "tofu",
         "veal" : "beets"
    },
    "seafood": {
        "shrimp": "vegan shrimp",
        "crab": "vegan crab",
        "lobster": "vegan lobster"
        
    },
    "misc": {
        "honey": "agave nectar",
        "gelatin": "agar agar",
        "fish sauce": "soy sauce",
        "caesar salad dressing": "miso dressing",
        "gravy": "vegatable broth and cornstarch mix",
        "lard": "olive oil",
        "pesto": "yeast pesto",
        "worcestershire sauce": "soy sauce"
    }
}

healthy_substitutions = {
    "sugar": "honey",
    "brown sugar": "coconut sugar",
    "confectioners' sugar": "coconut sugar",
    "corn syrup": "honey",
    "high-fructose corn syrup": "honey",
    "molasses": "honey",
    "butter": "coconut oil",
    "margarine": "coconut oil",
    "shortening": "coconut oil",
    "vegetable oil": "olive oil",
    "canola oil": "olive oil",
    "palm oil": "coconut oil",
    "corn oil": "olive oil",
    "white flour": "whole wheat flour",
    "white bread": "whole wheat bread",
    "white rice": "brown rice",
    "white pasta": "whole wheat pasta",
    "salt": "sea salt",
    "processed meats": "lean meats",
    "red meat": "poultry",
    "bacon": "turkey bacon",
    "sausage": "turkey sausage",
    "hot dogs": "tofu dogs",
    "ham": "turkey ham",
    "cheese": "nutritional yeast",
    "sour cream": "Greek yogurt",
    "mayonnaise": "avocado",
    "cream cheese": "Greek yogurt",
    "heavy cream": "coconut cream"
}
mexican_substitutions = {
    "olive oil": "vegetable oil",
    "balsamic vinegar": "lime juice",
    "red wine vinegar": "apple cider vinegar",
    "white wine vinegar": "distilled white vinegar",
    "parmesan cheese": "cotija cheese",
    "mozzarella cheese": "queso blanco",
    "ricotta cheese": "queso fresco",
    "feta cheese": "cotija cheese",
    "goat cheese": "queso de cabra",
    "blue cheese": "queso azul",
    "cream cheese": "queso crema",
    "sour cream": "crema",
    "yogurt": "crema",
    "tomatoes": "tomatillos",
    "sun-dried tomatoes": "chipotles in adobo",
    "basil": "cilantro",
    "thyme": "epazote",
    "rosemary": "oregano",
    "garlic": "jalapeno",
    "shallots": "red onion",
    "chicken": "chicken tinga",
    "beef": "carne asada",
    "pork": "chorizo",
    "seafood": "ceviche",
    "pasta": "enchiladas",
    "risotto": "arroz con pollo",
    "bread crumbs": "tortilla chips",
    "panko crumbs": "tortilla chips",
    "vegetable broth": "chicken broth",
    "white wine": "tequila",
    "beer": "Mexican beer",
    "bourbon": "mezcal",
    "rum": "tequila",
    "whiskey": "tequila",
    "brandy": "tequila",
    "butter": "ghee",
    "cream": "crema",
    "coconut milk": "crema de coco",
    "soy sauce": "mole",
    "hoisin sauce": "mole",
    "oyster sauce": "mole",
    "mayonnaise": "sour cream",
    "ketchup": "salsa",
    "mustard": "guacamole",
    "honey": "agave nectar",
    "brown sugar": "piloncillo",
    "maple syrup": "agave nectar",
    "bread": "tortillas",
    "granulated sugar": "piloncillo",
    "powdered sugar": "piloncillo",
    "brown rice": "arroz rojo",
    "white rice": "arroz blanco",
    "quinoa": "amaranth",
    "barley": "amaranth",
    "polenta": "masa harina",
    "cornstarch": "masa harina",
    "flour": "masa harina",
    "baking powder": "soda bicarbonato",
    "baking soda": "soda bicarbonato",
    "yeast": "levadura"
}

italian_substitutions = {
    "olive oil": "vegetable oil",
    "balsamic vinegar": "red wine vinegar",
    "white wine vinegar": "red wine vinegar",
    "parmesan cheese": "pecorino romano cheese",
    "mozzarella cheese": "provolone cheese",
    "ricotta cheese": "marscapone cheese",
    "feta cheese": "ricotta salata cheese",
    "goat cheese": "ricotta cheese",
    "blue cheese": "gorgonzola cheese",
    "cream cheese": "ricotta cheese",
    "sour cream": "plain Greek yogurt",
    "tomatoes": "sun-dried tomatoes",
    "basil": "oregano",
    "thyme": "marjoram",
    "rosemary": "sage",
    "garlic": "shallot",
    "chicken": "veal",
    "beef": "pork",
    "pork": "pancetta",
    "seafood": "clams",
    "pasta": "risotto",
    "bread crumbs": "panko crumbs",
    "vegetable broth": "chicken broth",
    "white wine": "chicken broth",
    "red wine": "beef broth",
    "beer": "red wine",
    "bourbon": "marsala wine",
    "rum": "marsala wine",
    "whiskey": "marsala wine",
    "brandy": "marsala wine",
    "butter": "olive oil",
    "cream": "evaporated milk",
    "soy sauce": "balsamic vinegar",
    "hoisin sauce": "soy sauce",
    "oyster sauce": "soy sauce",
    "mayonnaise": "ricotta cheese",
    "ketchup": "tomato paste",
    "mustard": "horseradish",
    "honey": "maple syrup",
    "brown sugar": "granulated sugar",
    "maple syrup": "honey",
    "bread": "polenta",
    "croissants": "panettone",
    "bagels": "ciabatta bread",
    "biscuits": "taralli",
    "pancakes": "crepes",
    "waffles": "crepes",
    "croutons": "bruschetta",
    "granola": "biscotti",
    "cereal": "biscotti",
    "muesli": "biscotti",
    "granulated sugar": "brown sugar",
    "powdered sugar": "granulated sugar",
    "brown rice": "risotto rice",
    "white rice": "risotto rice",
    "quinoa": "farro",
    "barley": "farro",
    "couscous": "orzo",
    "polenta": "mashed potatoes",
    "cornstarch": "flour",
    "baking powder": "yeast",
    "baking soda": "yeast",
}







